/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteDddArgs } from "./DeleteDddArgs";
import { DddFindManyArgs } from "./DddFindManyArgs";
import { DddFindUniqueArgs } from "./DddFindUniqueArgs";
import { Ddd } from "./Ddd";
import { DddService } from "../ddd.service";

@graphql.Resolver(() => Ddd)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class DddResolverBase {
  constructor(
    protected readonly service: DddService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Ddd",
    action: "read",
    possession: "any",
  })
  async _dddsMeta(
    @graphql.Args() args: DddFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Ddd])
  @nestAccessControl.UseRoles({
    resource: "Ddd",
    action: "read",
    possession: "any",
  })
  async ddds(@graphql.Args() args: DddFindManyArgs): Promise<Ddd[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Ddd, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Ddd",
    action: "read",
    possession: "own",
  })
  async ddd(@graphql.Args() args: DddFindUniqueArgs): Promise<Ddd | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ddd)
  @nestAccessControl.UseRoles({
    resource: "Ddd",
    action: "delete",
    possession: "any",
  })
  async deleteDdd(@graphql.Args() args: DeleteDddArgs): Promise<Ddd | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
